<?php require ("template/header.phtml") ?>

    <div class="container">
        <div id="products" class="row list-group">
            <?php foreach ($view->products as $product) { ?>
                <div class="item col-lg-4">
                    <div class="thumbnail">
                        <img src="<?php echo 'images/products/' . $product->getPhotoName()?>">
                        <div class="caption">
                            <h4 class="list-group-item-heading"><?php echo $product->getName()?></h4>
                            <div class="row">
                                <div class="col-md-6">
                                    <p class="lead"><?php echo "£".$product->getPrice()?></p>
                                </div>
                                <div class="col-md-6">
                                    <a href="productInfo.php?id=<?php echo $product->getId()?>">View Details</a>
                                </div>
                                <div class="col-md-6">
                                    <a href="cart.php?id=<?php echo $product->getId()?>">Add To Cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>

<?php require ("template/footer.phtml") ?>